package com.landlordcommunication.web.models;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "residences")
public class Residence {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idResidence")
    private int idResidence;

    @Column(name = "address")
    private String address;

    @Column(name = "landLordId")
    private int landlordId;

    @Column(name = "rent")
    private double rent;

    /*private <Something> image/image gallery;

   TODO figure how to store images - with URLs or binary objects

    */

    //to be populated via a SELECT query that uses join to gather info from 'users', 'LTR'
    //private List<Integer> tenantIds;

    public Residence() {
    }

    //autogenerated, could and most probably should be edited
    public Residence(int idResidence, String address, int landlordId, double rent, List<Integer> tenantIds) {
        setIdResidence(idResidence);
        setAddress(address);
        setLandlordId(landlordId);
        setRent(rent);
       // setTenantIds(tenantIds);
    }

    public int getIdResidence() {
        return idResidence;
    }

    private void setIdResidence(int idResidence) {
        this.idResidence = idResidence;
    }

    public String getAddress() {
        return address;
    }

    private void setAddress(String address) {
        this.address = address;
    }

    public int getLandlordId() {
        return landlordId;
    }

    private void setLandlordId(int landlordId) {
        this.landlordId = landlordId;
    }

    public double getRent() {
        return rent;
    }

    private void setRent(double rent) {
        this.rent = rent;
    }

    /*public List<Integer> getTenantIds() {
        return tenantIds;
    }

    private void setTenantIds(List<Integer> tenantIds) {
        this.tenantIds = tenantIds;
    }*/
}
