package com.landlordcommunication.web.models;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "residences")
public class Residence {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "address")
    private String address;

    @Column(name = "landLordId")
    private int landlordId;

    @Column(name = "rent")
    private double rent;

    /*private <Something> image/image gallery;

   TODO figure how to store images - with URLs or binary objects

    */

    //to be populated via a SELECT query that uses join to gather info from 'users', 'LTR'
    private List<Integer> tenantIds;

    public Residence() {
    }

    //autogenerated, could and most probably should be edited
    public Residence(int id, String address, int landlordId, double rent, List<Integer> tenantIds) {
        this.id = id;
        this.address = address;
        this.landlordId = landlordId;
        this.rent = rent;
        this.tenantIds = tenantIds;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public int getLandlordId() {
        return landlordId;
    }

    public void setLandlordId(int landlordId) {
        this.landlordId = landlordId;
    }

    public double getRent() {
        return rent;
    }

    public void setRent(double rent) {
        this.rent = rent;
    }

    public List<Integer> getTenantIds() {
        return tenantIds;
    }

    public void setTenantIds(List<Integer> tenantIds) {
        this.tenantIds = tenantIds;
    }
}
