package com.landlordcommunication.web.models;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "residences")
public class Residence {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int residenceId;

    @Column(name = "address")
    private String address;

    @Column(name = "rent")
    private double rent;

    @ManyToMany(mappedBy = "residences")
    private List<User> users = new ArrayList<>();

    /*private <Something> image/image gallery;

   TODO figure how to store images - with URLs or binary objects

    */

    //to be populated via a SELECT query that uses join to gather info from 'users', 'LTR'
    //private List<Integer> tenantIds;

    @ManyToMany(mappedBy = "residences")
    private List<User> user = new ArrayList<>();

    public Residence() {
    }

    //autogenerated, could and most probably should be edited
    public Residence(int residenceId, String address, double rent, List<Integer> tenantIds) {
        setResidenceId(residenceId);
        setAddress(address);
        setRent(rent);
       // setTenantIds(tenantIds);
    }

    public int getResidenceId() {
        return residenceId;
    }

    private void setResidenceId(int residenceId) {
        this.residenceId = residenceId;
    }

    public String getAddress() {
        return address;
    }

    private void setAddress(String address) {
        this.address = address;
    }

    public double getRent() {
        return rent;
    }

    private void setRent(double rent) {
        this.rent = rent;
    }

    /*public List<Integer> getTenantIds() {
        return tenantIds;
    }

    private void setTenantIds(List<Integer> tenantIds) {
        this.tenantIds = tenantIds;
    }*/

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
}
