package com.landlordcommunication.web.models;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;


@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int userId;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "surname")
    private String surname;

    @Column(name = "email")
    private String email;

    @Column(name = "budget")
    private double budget;

    // if true, user is a tenant, if false, user is a landlord - subject to redesign :)
    @Column(name = "is_tenant")
    private boolean isTenant;

    //to be defined via the LTR table

    public List<Residence> getResidences() {
        return residences;
    }

    public void setResidences(List<Residence> residences) {
        this.residences = residences;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "usertoresidence",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "residence_id")
    )
    private List<Residence> residences = new ArrayList<>();

    //to be populated with a query to the 'ratingRecords' table
    //private double rating;


    public User() {
    }


    //autogenerated, could and most probably should be edited
    public User(int id, String email, String firstName, String surname, boolean isTenant, double budget) {
        setUserId(id);
        setEmail(email);
        setFirstName(firstName);
        setSurname(surname);
        setIsTenant(isTenant);
        setBudget(budget);
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    /*public List<Residence> getResidences() {
        return residences;
    }

    public void setResidences(List<Residence> residences) {
        this.residences = residences;
    }*/

    public boolean getIsTenant() {
        return isTenant;
    }

    public void setIsTenant(boolean isTenant) {
        this.isTenant = isTenant;
    }

    public double getBudget() {
        return budget;
    }

    public void setBudget(double budget) {
        this.budget = budget;
    }

    /*public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }*/
}
